# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/lib_nbs/01_losses.ipynb.

# %% auto 0
__all__ = ['MSE', 'grad_MSE_lr']

# %% ../nbs/lib_nbs/01_losses.ipynb 2
import numpy as np

# %% ../nbs/lib_nbs/01_losses.ipynb 4
def MSE(x:np.ndarray, # x data of N elements
        y:np.ndarray, # y data of N elements
        fun:callable, # function $y=f(x)$
        params=None, # Parameters of the function in the form of a dictionary
       )->float:
    '''Given the data $x$ and $y$, this function computes the mean square error between $y$ and $y'=ax+b.$'''
    yp = fun(x) if params is None else fun(x,**params)
    MSE = np.mean((y-yp)**2)
    return MSE

# %% ../nbs/lib_nbs/01_losses.ipynb 6
def grad_MSE_lr(x:np.ndarray, # x data of N elements
                y:np.ndarray, # y data of N elements
                params: dict, # Parameters of the function
            )-> np.ndarray: # gradients
    '''Computes the gradient of the mean square error loss function with respect to $a$ and $b$ and returns np.array([$\partial_a$ MSE,$\partial_b$ MSE])'''
    a, b = params['a'], params['b']
    yp = a*x+b
    ga, gb = np.mean(2*x*(yp-y)), -np.mean(2*(yp-y))
    return np.array([ga,gb])
