# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/lib_nbs/04_utils.ipynb.

# %% auto 0
__all__ = ['show_code']

# %% ../nbs/lib_nbs/04_utils.ipynb 2
from IPython.display import Code
from inspect import getsource

# %% ../nbs/lib_nbs/04_utils.ipynb 3
def show_code(fun):
    '''Shows the source code of a function in the output of the cell.'''
    return Code(getsource(fun),language='python')
